"""Export the merged portfolio (+ scores + alerts) as CSV, JSON, and Markdown.

The Markdown file is the one to drag into a Claude Project — it carries the
numbers, the provenance metadata Claude needs to reason well, and an
analysis-only prompt.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

import pandas as pd

from .config import Config
from .fx import FxRate
from .models import SourceResult

log = logging.getLogger("stockerr.report")

DISCLAIMER = (
    "This report is generated by a personal, read-only tool for your own analysis. "
    "It is NOT investment advice and places no trades. Confidence scores are a "
    "systematic screen, not a recommendation or a guarantee — always do your own "
    "due diligence before deploying capital."
)

ANALYSIS_PROMPT = (
    "You are a portfolio analyst. Using ONLY the data in this report, analyze my "
    "portfolio: (1) overall net worth and asset allocation across stocks, mutual "
    "funds, and crypto; (2) concentration risk (any single holding or category too "
    "large); (3) currency exposure (INR vs USD/crypto); (4) how the confidence "
    "scores compare to my actual allocation (am I over/under-weight vs the scores?); "
    "and (5) specific, prioritized rebalancing ideas as ANALYSIS ONLY — do not tell "
    "me to auto-execute anything. Note any data gaps flagged in the metadata."
)


def _fmt_inr(x: float) -> str:
    return f"Rs.{x:,.2f}"


def _md_table(df: pd.DataFrame, columns: Optional[list[str]] = None) -> str:
    """Render a small Markdown table without needing the `tabulate` package."""
    if df is None or df.empty:
        return "_(none)_"
    cols = columns or list(df.columns)
    header = "| " + " | ".join(cols) + " |"
    sep = "| " + " | ".join("---" for _ in cols) + " |"
    lines = [header, sep]
    for _, row in df.iterrows():
        cells = []
        for c in cols:
            v = row[c]
            if isinstance(v, float):
                v = f"{v:,.2f}"
            cells.append(str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def build_metadata(fx: FxRate, source_results: list[SourceResult],
                   generated_at: datetime) -> dict:
    return {
        "generated_at": generated_at.isoformat(timespec="seconds"),
        "base_currency": "INR",
        "fx": {"pair": fx.pair, "rate": fx.rate, "source": fx.source,
               "fetched_at": fx.fetched_at},
        "sources": [
            {"source": r.source, "ok": r.ok, "count": len(r.holdings), "error": r.error}
            for r in source_results
        ],
    }


def write_reports(
    df: pd.DataFrame,
    cat_df: pd.DataFrame,
    fx: FxRate,
    source_results: list[SourceResult],
    cfg: Config,
    *,
    generated_at: datetime,
    alerts: Optional[list[str]] = None,
    scores_df: Optional[pd.DataFrame] = None,
) -> dict[str, Path]:
    alerts = alerts or []
    exports = cfg.exports_dir
    exports.mkdir(parents=True, exist_ok=True)
    date = generated_at.strftime("%Y-%m-%d")

    metadata = build_metadata(fx, source_results, generated_at)
    total = float(df["value_inr"].sum()) if not df.empty else 0.0

    # --- CSV (flat holdings) --------------------------------------------------
    csv_path = exports / f"holdings_{date}.csv"
    df.to_csv(csv_path, index=False, encoding="utf-8")

    # --- JSON (machine-readable artifact) -------------------------------------
    json_path = exports / f"holdings_{date}.json"
    payload = {
        "metadata": metadata,
        "total_net_worth_inr": round(total, 2),
        "allocation_by_category": cat_df.to_dict(orient="records"),
        "holdings": df.to_dict(orient="records"),
        "confidence_scores": (scores_df.to_dict(orient="records")
                              if scores_df is not None and not scores_df.empty else []),
        "alerts": alerts,
        "disclaimer": DISCLAIMER,
    }
    json_path.write_text(json.dumps(payload, indent=2, default=str), encoding="utf-8")

    # --- Markdown (paste into Claude) -----------------------------------------
    md_path = exports / f"report_{date}.md"
    md = [
        f"# Stockerr Portfolio Report — {date}",
        "",
        "## Metadata",
        f"- Generated: {metadata['generated_at']}",
        f"- Base currency: INR",
        f"- FX USD->INR: {fx.rate} (source: {fx.source}, at {fx.fetched_at})",
        "- Sources: " + ", ".join(
            f"{r.source}={'OK' if r.ok else 'FAILED'}"
            + (f" ({r.error})" if not r.ok and r.error else f" [{len(r.holdings)}]")
            for r in source_results
        ),
        "",
        f"## Net worth: {_fmt_inr(total)}",
        "",
        "## Allocation by category",
        _md_table(cat_df, ["category", "value_inr", "alloc_pct"]),
        "",
        "## Holdings",
        _md_table(df, ["asset", "category", "quantity", "price_inr", "value_inr",
                       "alloc_pct", "source"]),
        "",
    ]

    if scores_df is not None and not scores_df.empty:
        md += [
            "## Confidence scores (stocks)",
            "_0-100 screen: Fundamental x0.50 + Technical x0.30 + Sentiment x0.20. "
            "Decision support, not a recommendation._",
            _md_table(scores_df, [c for c in
                      ["symbol", "confidence", "fundamental", "technical", "sentiment", "notes"]
                      if c in scores_df.columns]),
            "",
        ]

    if alerts:
        md += ["## Alerts", *[f"- {a}" for a in alerts], ""]

    md += [
        "## Ask Claude",
        "```",
        ANALYSIS_PROMPT,
        "```",
        "",
        "---",
        f"_{DISCLAIMER}_",
    ]
    md_path.write_text("\n".join(md), encoding="utf-8")

    log.info("Wrote %s, %s, %s", csv_path.name, json_path.name, md_path.name)
    return {"csv": csv_path, "json": json_path, "markdown": md_path}
